### ISSUE TITLE
Peer to Peer code review (Mre, Mihreteab, Santi)

### ISSUE THREAD

**Issue by vechicin** [Lucas-Masaba/my_portfolio#9]
In the "About Myself" section try increasing the padding to see if you like the result, it is better to set margins and padding in percentages.

In the "Projects" section, try decreasing the margins between each project card to see if you like it better!

Delete comments unless they separate sections in both HTML and CSS files. This improves code readability. 

Make sure your "alt" clauses in the images tags are more descriptive. This goes a long way towards improving your page's SEO and making it more friendly to use for disabled users.

**Comment by Lucas-Masaba** [comment]
Thank you so much for that. I did all the changes
